# Generated by Django 5.0 on 2024-01-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='payment_option',
            field=models.CharField(default='cash_on_delivary', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_main_data',
            name='order_status',
            field=models.CharField(max_length=100),
        ),
    ]
