# Generated by Django 5.0 on 2024-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0002_order_main_data_payment_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_main_data',
            name='order_status',
            field=models.CharField(default='Order Placed', max_length=100),
        ),
    ]
