# Generated by Django 5.0 on 2024-01-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0003_alter_order_main_data_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_main_data',
            old_name='price',
            new_name='total_price',
        ),
    ]
