# Generated by Django 5.0 on 2024-01-06 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0004_rename_price_order_main_data_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_main_data',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
