# Generated by Django 5.0 on 2024-01-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0006_alter_order_main_data_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_main_data',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
