# Generated by Django 5.0 on 2024-01-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0007_alter_order_main_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='order_details',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
