# Generated by Django 5.0 on 2024-01-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0008_order_main_data_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_main_data',
            old_name='order_details',
            new_name='order_id',
        ),
    ]
