# Generated by Django 5.0 on 2024-01-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0009_rename_order_details_order_main_data_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sub_data',
            name='quantity',
        ),
    ]
