# Generated by Django 5.0 on 2024-01-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0010_remove_order_sub_data_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sub_data',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
