# Generated by Django 5.0 on 2024-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0011_order_sub_data_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order_sub_data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
