# Generated by Django 5.0 on 2024-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0012_order_main_data_is_active_order_sub_data_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
