# Generated by Django 5.0 on 2024-01-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0013_order_main_data_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='payment_id',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
