# Generated by Django 5.0 on 2024-01-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0014_order_main_data_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='country',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='district',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='house_name',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='name',
            field=models.CharField(default='sarath', max_length=50),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='phone_number',
            field=models.CharField(default='null', max_length=40),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='pin_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='state',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='order_main_data',
            name='street_name',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
