# Generated by Django 5.0 on 2024-01-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0015_order_main_data_country_order_main_data_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_main_data',
            name='address',
        ),
    ]
