# Generated by Django 5.0.1 on 2024-01-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_managements', '0016_remove_order_main_data_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_main_data',
            name='coupon_discount',
            field=models.IntegerField(null=True),
        ),
    ]
