# Generated by Django 5.0 on 2024-01-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
