# Generated by Django 5.0 on 2024-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_address_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
            ],
        ),
    ]
