# Generated by Django 5.0 on 2024-01-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0010_transaction_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='wallet_amount',
        ),
    ]
