# Generated by Django 5.0 on 2023-12-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=40, unique=True)),
                ('brand_image', models.ImageField(upload_to='brand_images')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
