# Generated by Django 5.0 on 2024-01-20 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_codes',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
