# Generated by Django 5.0 on 2024-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0004_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
        migrations.AddField(
            model_name='users_coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
