# Generated by Django 5.0 on 2024-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0006_coupon_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_coupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='users_coupon',
            name='is_active',
        ),
        migrations.AddField(
            model_name='users_coupon',
            name='coupon_code',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='users_coupon',
            name='coupon_discount',
            field=models.IntegerField(default=1),
        ),
    ]
