# Generated by Django 5.0 on 2024-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0007_remove_users_coupon_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_coupon',
            name='coupon_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users_coupon',
            name='coupon_discount',
            field=models.IntegerField(null=True),
        ),
    ]
