# Generated by Django 5.0 on 2024-02-08 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0008_alter_users_coupon_coupon_code_and_more'),
        ('order_managements', '0017_order_main_data_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_coupon',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_managements.order_main_data'),
        ),
    ]
