# Generated by Django 5.0 on 2024-02-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0009_users_coupon_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_coupon',
            old_name='order_id',
            new_name='order',
        ),
    ]
