# Generated by Django 5.0 on 2023-12-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_rename_product_product_variant_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_images',
            old_name='user_id',
            new_name='user',
        ),
    ]
