# Generated by Django 5.0 on 2023-12-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_products_images_delete_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='C:\\Users\\sarat\\Documents\\ noimage.jpg', upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.products')),
            ],
        ),
    ]
