# Generated by Django 5.0 on 2023-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_remove_products_images_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_images',
            name='thumbnail',
            field=models.ImageField(default='C:\\Users\\sarat\\Documents\\ noimage.jpg', upload_to='thumbnail_images'),
        ),
    ]
