# Generated by Django 5.0 on 2023-12-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_alter_product_images_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_images',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail_images'),
        ),
    ]
