# Generated by Django 5.0 on 2023-12-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_remove_product_images_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variant',
            old_name='color',
            new_name='colour',
        ),
    ]
