# Generated by Django 5.0 on 2023-12-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_rename_color_product_variant_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_slug',
        ),
    ]
