# Generated by Django 5.0 on 2023-12-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_remove_products_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='stock',
        ),
    ]
