# Generated by Django 5.0 on 2023-12-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0013_remove_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail_images'),
        ),
    ]
