# Generated by Django 5.0 on 2023-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0014_remove_product_variant_thumbnail_products_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_variant',
            old_name='colour',
            new_name='colour_code',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='colour_name',
            field=models.CharField(default='DefaultColour'),
        ),
    ]
