# Generated by Django 5.0 on 2023-12-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0015_rename_colour_product_variant_colour_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='colour_name',
            field=models.CharField(),
        ),
    ]
