# Generated by Django 5.0 on 2023-12-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0016_alter_product_variant_colour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
