# Generated by Django 5.0 on 2024-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0018_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='variant_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
