# Generated by Django 5.0 on 2023-12-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0002_remove_category_category_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
