# Generated by Django 5.0 on 2024-01-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.DateField(default='2024-01-21'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='category',
            name='minimum_amount',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
