# Generated by Django 5.0 on 2024-01-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0006_alter_category_discount_alter_category_expirydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
